In [1]:
#1.creating numpy n-d/array
import numpy as np

In [2]:
arr1=np.array([1,3,5,6]) #1.method
arr1

array([1, 3, 5, 6])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2 = np.array([[1,2,3],[1,2,3]])#2.method 2d array
arr2

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
#for initailzing the array use the zeros function #3.method
arr4 = np.zeros((2,3))#2 is the row and 3 is col(it is inside the shape of tuple)give's a empty array
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr5= np.ones((3,3))#by default it is a float #4.method
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr6 = np.identity(5)# this matrix print digonally one's and remaning are zero's #5.method
arr6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
arr7 = np.arange(10)#it will be create a array range in a given range #6.method
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr8 = np.linspace(10,20,10)#7.method start index is 10,ending index 20 and their data will be 0 to 9
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [10]:
arr10 = np.array([3,3])#8.method
arr11 = arr10.copy() #copy the array
arr11

array([3, 3])

In [11]:
# 2.Array Properties and atributes------------------------------------------------------------

In [12]:
arr1 # we can used here prev one

array([1, 3, 5, 6])

In [13]:
#shape is an attribute 
arr1.shape # which is 4 col and 0 row

(4,)

In [14]:
arr2

array([[1, 2, 3],
       [1, 2, 3]])

In [15]:
arr2.shape

(2, 3)

In [16]:
arr12 = np.array([[1,2,3],[1,2,3]])
arr12

array([[1, 2, 3],
       [1, 2, 3]])

In [17]:
arr13= np.array([  [  [  [ 1,2],[3,4],[92,2] ],[[4,6],[29,4],[19,1 ]   ] ]]) #it is a 3d array
arr13

array([[[[ 1,  2],
         [ 3,  4],
         [92,  2]],

        [[ 4,  6],
         [29,  4],
         [19,  1]]]])

In [18]:
arr13.shape # gives the shape of array

(1, 2, 3, 2)

In [19]:
arr13.ndim #give's the dimenshions and it is a attribute

4

In [20]:
arr1

array([1, 3, 5, 6])

In [21]:
arr1.size #give's the size of array

4

In [22]:
arr13.size

12

In [23]:
arr13.itemsize # each occupies the 4byte memory that's why it's give a 4

4

In [24]:
arr1.itemsize #same here also

4

In [25]:
arr2

array([[1, 2, 3],
       [1, 2, 3]])

In [26]:
arr2.itemsize

4

In [27]:
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
arr5.itemsize #it's give a 8 because the size of data is 8 bytes and they are a float

8

In [29]:
arr2

array([[1, 2, 3],
       [1, 2, 3]])

In [30]:
arr2.dtype # data type of arr2 is int

dtype('int32')

In [31]:
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr5.dtype # data type is float

dtype('float64')

In [33]:
arr5.astype('float')# convert int to float means typecasting

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
arr15 =np.array([["abhi"],["ani"],["meena"],["pravin"]])
arr15

array([['abhi'],
       ['ani'],
       ['meena'],
       ['pravin']], dtype='<U6')

In [35]:
arr15.dtype

dtype('<U6')

In [36]:
arr15.itemsize

24

In [37]:
arr15.size

4

In [38]:
#3.Indexing ,Slicing and iteration------------------------------------------------

In [39]:
a1=np.arange(24).reshape(6,4) # with the help of reshape we can change the rows and columns
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
arr1[2]# it is same like a array indexing ok abhishek
arr1[1:3]
arr1[-1]

6

In [41]:
a1[2:3] #slicing 

array([[ 8,  9, 10, 11]])

In [42]:
a1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [43]:
a1[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [44]:
a1[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [45]:
a1[4:,2:]

array([[18, 19],
       [22, 23]])

In [46]:
a1[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [47]:
a1[4:,:2]

array([[16, 17],
       [20, 21]])

In [48]:
#iteration
for i in a1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [49]:
for i in np.nditer(a1): #np.nditer is build in function in numpy 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [50]:
#4. Numpy Operations------------------------------------------------------

In [51]:
arr1 = np.array([1,2,3,4,5,6])
arr2= np.array([4,5,6,7,8,9])

In [52]:
arr1 - arr2  #sub

array([-3, -3, -3, -3, -3, -3])

In [53]:
arr1 * arr2 #vector mulication ( such as arr1 and arr2 treatd as a vector so that's why called vector)

array([ 4, 10, 18, 28, 40, 54])

In [54]:
arr1*2 #it is a scaler mulitiplication(arr1 is vector here and 2 is the scaler value so it is a scaler)

array([ 2,  4,  6,  8, 10, 12])

In [55]:
arr2>3 #where the condition is satisfied in arr2 it is print true

array([ True,  True,  True,  True,  True,  True])

In [56]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [57]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [59]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [60]:
arr1.dot(arr3)

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [ ]:
arr3

In [64]:
arr3.min()

0

In [65]:
arr3.max()

5

In [61]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [62]:
arr4.min(axis=0) #print column wise min value

array([6, 7])

In [63]:
arr4.min(axis=1) # print row wise min value

array([ 6,  8, 10])

In [67]:
arr4.max(axis=0) # print col wise max value

array([6, 7])

In [68]:
arr4.max(axis=1)# print row wise max value

array([ 7,  9, 11])

In [69]:
arr4.sum() #print the sum of whole array

51

In [70]:
arr4.sum(axis=0) #print the sum of col wise

array([24, 27])

In [71]:
arr4.sum(axis=1) #print the sum of col wise

array([13, 17, 21])

In [72]:
arr4.mean() #caculate the mean,(sum of array / no.of elements in array)=mean ex: 51/6=8.5}

8.5

In [73]:
arr4.std() # please check here:  https://www.geeksforgeeks.org/numpy-std-in-python/

1.707825127659933

In [74]:
np.median(arr4)

8.5

In [75]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [ ]:
np.cos(arr4)

In [ ]:
np.exp(arr4)

In [ ]:
#5 Reshaping numpy array--------------------------------------------------------

In [77]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [76]:
arr4.ravel() #it convert n dimentions to 1D array

array([ 6,  7,  8,  9, 10, 11])

In [78]:
arr4.transpose() # rows are col and col are row

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [ ]:
arr5 = np.arange(12,18).reshape(2,3)
arr5

In [ ]:
arr6 =np.arange(18,24).reshape(2,3)
arr6

In [ ]:
np.hstack((arr5,arr6)) #h-stack (horizontal stack) add the 2 array horizontally

In [ ]:
np.vstack((arr5,arr6)) #h-stack (vertically stack) add the 2 array vertizontally

In [ ]:
arr3

In [ ]:
np.hsplit(arr3,3) #horizontall split 

In [ ]:
np.vsplit(arr3,2)

In [ ]:
#6. indexing and boolean arrays------------------------------------------------
import numpy as np

In [ ]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

In [ ]:
arr[arr>50] #only those elemenet are remaining which has satisfied the condtition

In [ ]:
arr[(arr<30)&(arr%2==0)] #these is saying the indexing with boolean array 

In [ ]:
arr[(arr<30)&(arr%2==0)]=0 #these is saying the indexing with boolean array 
arr

In [ ]:
#fancy indexing 
import numpy as np
arr8=np.arange(24).reshape(6,4)
arr8

In [ ]:
arr8[[0,2,4]] #stars from 0 and 2 rows here and 4 columns

In [ ]:
#7.Plotting graphs using Numpy---------------------------------

In [ ]:
x = np.linspace(-10,10,20)# starts from -10 and end at 10 including 20 elements
x

In [ ]:
x.size


In [ ]:
y =np.sin(x) #create an variale which store the sin of x data
y

In [ ]:
y.size

In [ ]:
import matplotlib.pyplot as plt #inside matplotlib pyplot the graphs are available  #this is use for print or say stay on the screen as a getc in c
%matplotlib inline

In [ ]:
plt.plot(x,y)

In [ ]:
y=x*x+2*x+6   #this is the qudratic equation

In [ ]:
plt.plot(x,y)

In [ ]:
y = x+x+x
plt.plot(x,y)

In [ ]:
y = np.linspace(1,5,5)
y

In [ ]:
import matplotlib.pyplot as plt


In [ ]:
y =x+x
plt.plot(x,y)

In [ ]:
#8- Broadcasting----------------------------------------------------

In [ ]:
#scenario-1
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)
print(a1)
print(a2)

In [ ]:
a1+a2

In [ ]:
#scenario-2
a3=np.arange(9).reshape(3,3)
a4=np.arange(3).reshape(1,3)
print(a3,a4)

In [ ]:
a3+a4

In [ ]:
#-9--------------------------------numpy functions-----------------------------------

In [ ]:
np.random.random()

In [ ]:
np.random.seed(1)
np.random.random()

In [ ]:
np.random.uniform(1,10)

In [ ]:
np.random.uniform(1,10,10).reshape(2,5)

In [ ]:
np.random.randint(1,10,10).reshape(2,5)

In [ ]:
a=np.random.randint(1,50,6)

In [ ]:
np.sort(a)

In [ ]:
np.percentile(a,2)

In [ ]:
# End numpy